`stages:
  - test
  - verify
  - name: deploy
    if: branch = master

language: java

jdk:
  - openjdk8
#  - oraclejdk8
  - openjdk12
#  - ibmjdk8

install:
  - java -version
  - which javadoc
  - env | sort

jobs:
  include:
    - stage: test
      script:
        - ./mvnw -B -U clean test
    - stage: verify
      script: echo verify
    - stage: deploy
      script: echo deploy


cache:
  directories:
    - $HOME/.m2
