os: linux
group: edge
dist: trusty

stages:
  - test
  - verify
  - name: deploy
    if: repo = "HonoluluHenk/gcmonitor" AND branch in (master, develop)

language: java
jdk:
  - openjdk8
  - oraclejdk8

script: ./mvnw -B -U test

install:
  - java -version
  - env | sort

matrix:
  fast_finish: true
  include:
    - stage: verify
      script: ./mvnw -B -U verify
      jdk: openjdk12

    - stage: deploy
      script: ./mvnw --settings deploy/settings.xml -B -U -Pdeploy-only deploy
      jdk: openjdk12

cache:
  directories:
    - $HOME/.m2
