os: linux
group: edge
dist: trusty

stages:
  - test
  - name: verify
    if: branch != master
  - name: verify-deploy
    if: branch = master

language: java
#jdk:
#  - openjdk8
#  - oraclejdk8
#
#script: ./mvnw -B -U clean test

install:
  - java -version
  - env | sort

jobs:
  include:
    - stage: verify
      script: ./mvnw -B -U clean verify
      jdk: openjdk12

    - stage: verify-deploy
      script: ./mvnw -B -U clean verify deploy
      jdk: openjdk12

cache:
  directories:
    - $HOME/.m2
