os: linux
group: edge
dist: trusty

stages:
  - test
  - name: test-verify
    if: branch != master
  - name: test-verify-deploy
    if: branch = master

language: java
jdk:
  - openjdk8
  - oraclejdk8
  - openjdk12

script: ignore

install:
  - java -version
  - which javadoc
  - env | sort

matrix:
  include:
    - stage: test
      script:
        - ./mvnw -B -U clean test
      jdk:
        - openjdk8
        - oraclejdk8

    - stage: test-verify
      script: ./mvnw -B -U clean verify
      jdk:
        - openjdk12

    - stage: test-verify-deploy
      script: ./mvnw -B -U clean verify
      jdk:
        - openjdk12

  exclude:
    - stage: test
      jdk: openjdk12
    - stage: test-verify
      jdk:
      - openjdk8
      - oraclejdk8
    - stage: test-verify-deploy
      jdk:
      - openjdk8
      - oraclejdk8

cache:
  directories:
    - $HOME/.m2
