stages:
  - test
  - name: test-verify
    if: branch != master
  - name: test-verify-deploy
    if: branch = master

language: java

script: true

install:
  - java -version
  - which javadoc
  - env | sort

jobs:
  include:
    - stage: test
      script:
        - ./mvnw -B -U clean test
      jdk:
        - openjdk8
        - oraclejdk8
        - ibmjdk8
    - stage: test-and-verify
      script: ./mvnw -B -U clean verify
      jdk:
        - openjdk12
    - stage: test-verify-deploy
      script: ./mvnw -B -U clean verify
      jdk:
        - openjdk12


cache:
  directories:
    - $HOME/.m2
